### ISSUE TITLE
firefox: The binary is outdated. Please download or build a more recent one.

### ISSUE THREAD

**Issue by m040601** [SamHH/bukubrow-webext#112]
Hi, I'm on Arch Linux   5.0.10-arch1-1-ARCH x86_64 GNU/Linux using Firefox.

1. I've built bukubrow-host :

- with make build-linux-x64, extracted the zip file and moved the binary "bukubrow-linux-x64" to $PATH.
- I then did bukubrow-linux-x64 --install-firefox
- a file, com.samhh.bukubrow.json, was created in $HOME/.mozilla/native-messaging-hosts/
- it contains
`{"name":"com.samhh.bukubrow","description":"Bukubrow host for the Firefox extension","path":"/correct/path/to/my/bin/folder/bukubrow-linux-x64","type":"stdio","allowed_extensions":["bukubrow@samhh.com"]}
`
2. I installed bukubrow-webext from Mozilla addons:
- from, https://addons.mozilla.org/en-US/firefox/addon/bukubrow/
Version 3.0.0(Apr 28, 2019)

On Firefox when I click the button I get

> The binary is outdated. Please download or build a more recent one

3. I tried to build the extension myself:
- follow exactly what is said at https://github.com/SamHH/bukubrow-webext/
- git clone make webext

make prepare
make[1]: Entering directory '/dev/shm/bukubrow-webext'
mkdir -p .build release
make[1]: Leaving directory '/dev/shm/bukubrow-webext'
cd webextension && yarn && yarn build
bash: line 0: cd: webextension: No such file or directory
make: *** [makefile:30: webext] Error 1

Could it be that the released version on addons.mozilla.org is outdated ?
If so could you make an effort to keep it updated with changes in the source code ?
I dont even want to try building the extension myself. It's a big polluting mess with node/npm packages in your system if you're no a developer. 
> Load the extension in your browser. Please refer to the browser documentation.

Nowadays It's also a nightmare trying to load a non official non signed extension.
Unless the whole bukubrow host/extension setup runs smooth and flawless, this is never gonna work out, if it's catering to the average buku user. I

PS: See also my 2 cents, trying to make the bukubrow host/extension as simple, clean and straightforward for end users as possible. 
https://github.com/SamHH/bukubrow-webext/issues/85

**Comment by SamHH** [comment]
Hey, I just split the repo up into two separate ones and as such the documentation is a little ahead of itself, my apologies for that. For the present build of the webext you'll need the old version of the binary from this repo, specifically from this commit: https://github.com/SamHH/bukubrow-webext/tree/656a17761ee5504e300c0ad7492b9e8fbe4754ef

I'm hoping to have a proper updated release for each repo out this weekend, I was optimistic that the project was small enough that nobody would notice... I have been proven wrong. :stuck_out_tongue:

**Comment by SamHH** [comment]
Releases have been made for each repo (`4.0.0` and `4.0.0.1`). The host has pre-built binaries available in the releases page, and the webext update has been pushed to each the Firefox and Chrome addon stores (though they're being verified and may not be immediately available). In each case you can optionally build yourself as well, it should work.

**Comment by m040601** [comment]
>  I was optimistic that the project was small enough that nobody would notice... 

Maybe because you're the developer and it's obvious to you what needs to be done to make buku a great browser independent bookmark manager.

But for 99 percent of potential buku end users (not developers) this is the missing piece to make buku itself much more interesting..

Hope when bukubrow get more thoughly testing and polish, it get can get more prominence on buku's own page.

Another personal suggestion of mine.
Make it crystal clear for end users. It's not obvious for everyone this need for a host "glue" and an extension. That means always pay attention to the text you write https://addons.mozilla.org/en-US/firefox/addon/bukubrow/ .

I think it's good enough. But maybe you could standardize and change the name of the mozilla from "bukubrow" to "bukubrow-webext" or "bukubrow-firefox" ? You also need to update the link, still has https://addons.mozilla.org/en-US/firefox/addon/bukubrow/

Sorry if I'm being picky. But again, I'm just reminding you that what seems "obvious" to a developers is not for an end user. Besides the more you invest in crystal clear instructions for end users, the more time you'll save yourself in answering questions .
