### ISSUE TITLE
Provide different error message if host is too new

### ISSUE THREAD

**Issue by SamHH** [SamHH/bukubrow-webext#114]
Also update terminology to use "host" instead of "binary".

**Comment by razic** [comment]
heya quick question. i think this broke for me today. this line checks to see if the version is 3 parts https://github.com/SamHH/bukubrow-webext/blob/483491e937354fbb2ef3fb8c61e8cea2948091d3/src/modules/semantic-versioning.ts#L6 but i think with the 4.0.0.1 release it will always return false. i built the host from the master branch.

**Comment by razic** [comment]
also i'm not sure 4.0.0.1 follows the https://semver.org/ format. usually its only 3 parts

**Comment by SamHH** [comment]
It broke for you today as the webext `4.0.0.1` update (from `3.0.0`) finally got pushed out by Mozilla, you can grab an updated host [here](https://github.com/SamHH/bukubrow-host/).

That code is checking the version of the host which _does_ follow semver. The webext doesn't and is designed to denote compatibility with the host, so support is e.g.:

- host `1.0.0` -> webext `1.0.0.1`, `1.0.0.2` etc
- host `1.1.0` -> webext `1.0.0.1`, `1.0.0.2`, `1.1.0.1`, etc
- host `2.0.0` -> webext `2.0.0.1`, etc

As a rule of thumb you can just keep both the webext and the host up to date and it'll be fine, this weekend was a fairly unique situation in which that wasn't the case due to Mozilla's issues.

I wanted to make the versioning clearer on the webext's side (e.g. `4.0.0-r1` was my plan) however unfortunately one of the browser manifests, I think Chrome's, was quite strict in the documentation about versioning. This was the compromise I came up with.

As for the logic regarding following semver, the host is an API of sorts which the webext depends upon. The webext on the other hand is strictly a consumer so there's no need for it to follow semver.

**Comment by SamHH** [comment]
https://github.com/SamHH/bukubrow-webext/commit/c91342422b5460b88406851f983cf113d2b26cbb
