### ISSUE TITLE
Getting the following error: "The binary is outdated. Please download or build a more recent one." in both Firefox and Chrome

### ISSUE THREAD

**Issue by andrewmercerCA** [SamHH/bukubrow-webext#115]
In the past few days I've started getting this error when trying to add a bookmark in both Chrome and Firefox. Chrome stopped working first sometime over the weekend, then firefox stopped working today. I updated my version of buku, tried re-installing the browser add-ons and building a new host (which I was unable to get working).

Thanks in advance for any help!

**Comment by SamHH** [comment]
This might be caused to: https://github.com/SamHH/bukubrow-host/issues/10

Let's address that one first.

**Comment by SamHH** [comment]
Hey @andrewmercerCA, was this solved with the host fix?

**Comment by andrewmercerCA** [comment]
@SamHH Indeed it was, thanks!
