### ISSUE TITLE
Preference to turn of domain count badge?

### ISSUE THREAD

**Issue by rnkn** [SamHH/bukubrow-webext#117]
Hello,

Thank you for creating Bukubrow. I love it.

Would you consider adding a preference to toggle the domain count badge?

**Comment by SamHH** [comment]
This feature will be included in the next release: https://github.com/SamHH/bukubrow-webext/commit/42bd51febf578da0311df8b46a7960651d5cb91c

**Comment by rnkn** [comment]
Thanks!
