### ISSUE TITLE
Change the way tags are added

### ISSUE THREAD

**Issue by xaltsc** [SamHH/bukubrow-webext#119]
The current way of adding tags is cumbersome if you want to add many, it requires you to leave the keyboard and use the mouse. We should either be able to add tags by separating words with a comma or by preceding words by a '#'.

**Comment by SamHH** [comment]
You can just hit `Enter`.

**Comment by xaltsc** [comment]
Thanks, I didn't know that. I still think it would be great if we could add tags this way, the way that tumblr did (and still does perhaps). I don't see any reasonable use cases where someone would use a comma in their tags.

PS: keep up the good work !
