### ISSUE TITLE
Does bukubrow have hotkeys

### ISSUE THREAD

**Issue by E3D3** [SamHH/bukubrow-webext#124]
Issue #7 "Make hotkeys configurable" suggest that this extension had hotkeys. Is this still the case, and if so, where to find those keybindings ?

**Comment by SamHH** [comment]
There are, but per #107 they're not really documented anywhere yet and have just been added where I've found a need for them personally.

At present, you can open Bukubrow with [Ctrl+Shift+B](https://github.com/SamHH/bukubrow-webext/blob/master/src/assets/manifest.json#L29).

You can focus the bookmarks list input with [Ctrl+L](https://github.com/SamHH/bukubrow-webext/blob/master/src/containers/search-controls.tsx#L87), though I can't remember why that'd be necessary.

It's also possible to use the [Up/Down arrow keys and Enter](https://github.com/SamHH/bukubrow-webext/blob/master/src/containers/bookmarks-list.tsx#L37) to navigate the bookmark list.

The bookmark add/edit form behaves as any well-behaved web form and allows you to Tab and Enter around the fields. Hitting Enter when the tags input is focused will add the tag.

If you'd like to make a feature request regarding keyboard navigation then #107 would be the place to do that.

Hope that helps.
