### ISSUE TITLE
bookmarklets don't work

### ISSUE THREAD

**Issue by E3D3** [SamHH/bukubrow-webext#127]
bukubrow doesn't execute bookmarklets, javascript as url, e.g.
`javascript:void(document.body.style.fontSize='20px')`
This should set the font size of current webpage to 20 px.

**Comment by SamHH** [comment]
This is probably doable.

For implementation, we can consider any bookmark with a URL starting with `javascript:` as a bookmarklet, it'll affect anywhere we're creating `URL`s, and we'll probably need some new permissions in order to execute bookmarklets in the active tab.

**Comment by E3D3** [comment]
Thank you, also for sharing the nice bukubrow, that makes buku complete for me.

**Comment by SamHH** [comment]
This feature is now live on Firefox and will be live on Chrome as soon as it passes "review" :confetti_ball:
