### ISSUE TITLE
information

### ISSUE THREAD

**Issue by E3D3** [SamHH/bukubrow-webext#129]
Some information about input filters and hotkeys, in the README or on the webbrowser addons-page would make this program even nicer, IMHO.

**Comment by SamHH** [comment]
I've added some information about filtering to the README. I'm not documenting hotkeys yet as they're nowhere near complete, but feedback and feature requests in #107 are welcome. :slightly_smiling_face:

**Comment by E3D3** [comment]
Much better IMO. Now simple minds like me know how to enjoy bukubrow even more.
'Maybe' also add that people can/should search 'Issues' to find experimental hotkeys etc.

Bookmarklets still don't work here when called from bukubrow,
and my bukubrow Chromium extension doesn't work at all, shows an empty popup.
Here a screenshot [https://paste.pics/e6596fd99bb6e3fefe5532b294d7d81a](url) .
I've build the latest host (today) and installed the extension from the Firefox and Chromium addon pages.

**Comment by SamHH** [comment]
Hmm, bookmarklets are working for me in both Firefox and Chrome. Could you test with the example bookmarklet in the README? It works on GitHub. If that works, then what code is failing to work?

**Comment by E3D3** [comment]
I'm becoming crazy; the same bookmarklets that I tried for more than a week now suddenly works (in Firefox); my, yours & other examples !? I guess I need to reboot my laptop again, after 2 months, because its getting more quircks, or give myself an electroshock. Because I rarely use Chromium, you can close this issue.
I'm really  sorry for waisting your time with this and thanks again.

**Comment by LeXofLeviafan** [comment]
I believe this information (at least the search filters) should be mentioned in the webbrowser addon pages (or at least mentioned, but there's not much of it so it would make sense to simply include it).

…Incidentally, I would also suggest to place a wiki link in the bookmarklet item, for clarity (e.g. "[Bookmarklet](https://en.wikipedia.org/wiki/Bookmarklet)").
