### ISSUE TITLE
Feature Request:  Add compatibility with Vivaldi Browser

### ISSUE THREAD

**Issue by watsond** [samhh/bukubrow-webext#148]
**Feature Request:   Add compatibility with Vivaldi Browser**

From Chrome Web Store, the Bukubrow extension installs into Vivaldi browser without error.

But, attempting to actually run Bukubrow produces the message  "An unknown error occurred".  (See screenshot.)
After disabling other extension, the error still occurs.

Bukubrow works great with Firefox and Chromium.
Bukubrow functionality within Vivaldi would be much appreciated!

![Bukubrow-Failure](https://user-images.githubusercontent.com/3053145/90355292-8f367c80-e011-11ea-86e1-4dd3bce17550.png)

**Comment by samhh** [comment]
Almost certainly a case of the host needing to add support, created a ticket over there: https://github.com/samhh/bukubrow-host/issues/27
