### ISSUE TITLE
Are tag picklists possible?

### ISSUE THREAD

**Issue by henrythemouse** [samhh/bukubrow-webext#149]
I just started using bukubrow and would like to suggest two tag related features.

1) When I enter a # to search for a tag, it would be nice to hit the enter key (or a button) to bring up a list of tags. Just like doing "buku -t" in the terminal. Even better if the list members were selectable.

2) When editing or creating bookmarks it would also be helpful to have a way to display a list of available tags to add.

I'd also like to take this opportunity to thank you for providing this extension, it's the best bookmark utility I've ever used. You leverage the features of buku brilliantly. I am finally able to use one bookmark db for multiple browsers  across multiple systems. Thanks.

**Comment by samhh** [comment]
I think this is covered by #98?

**Comment by henrythemouse** [comment]
#98 certainly seems to cover it, and then some. HTML datalist gets the job done well enough. I'm not a fan of going into ordering complexities based on page content or my last Amazon order. ;-) To me  buku functionality keeps it fast and simple, two attributes I like. The other way starts to look more like what wallabagger does which creates unnecessary delays and even misdirection. I think that picklists are one thing and suggestions are another.

Do you intend to use datalist?

**Comment by samhh** [comment]
At the moment I don't know, I actually don't use Bukubrow any more myself, preferring a Git repo of text files similar to [pass](https://www.passwordstore.org/), and using a niche browser (vimb) that doesn't support WebExtensions anyway.

But I do intend to keep maintaining it. I have more time for open source now than I have done but am currently writing a terminal podcast fetcher in Haskell. Contributions welcome of course :wink:

**Comment by henrythemouse** [comment]
Thanks for the heads up. For me this added functionality would make 
bukubrow complete. Unfortunately, I don't have the dev skills to 
accomplish this. I hope you get to do it. And thank you for the link to 
'pass', it looks interesting. I'd like to give it try.

Happy trails.
