### ISSUE TITLE
Firefox extension  trows unknown error.

### ISSUE THREAD

**Issue by GeorgiKarapetrov** [samhh/bukubrow-webext#162]
**OS:** Arch Linux
**Kernel:** 5.12.1-zen2-1-zen
**Browser:** Mozilla Firefox 88.0.1
**Buku version:** 4.5
**Bukubrow installation source:** The Firefox add-on store.

**Expected behavior:** bukubrow connects to buku and displays my bookmarks.

**Actual behavior:** Clicking on the bukubrow icon gives the following error screen:
![image](https://user-images.githubusercontent.com/47497662/117566307-98dfa300-b0be-11eb-98cf-11b0125403e3.png)
None of the buttons are clickable. The search bar is also non-clickable.
<br/><br/>I ran a debug console. The relevant error may be:
```
sendRemoveListener on closed conduit bukubrow@samhh.com.412316863934 ConduitsChild.jsm:108
    _send resource://gre/modules/ConduitsChild.jsm:108
    _send self-hosted:1277
    removeListener resource://gre/modules/ExtensionChild.jsm:663
    removeListener resource://gre/modules/ExtensionChild.jsm:886
    onClicked chrome://browser/content/child/ext-menus.js:284
    removeListener resource://gre/modules/ExtensionCommon.jsm:2523
    revoke resource://gre/modules/ExtensionCommon.jsm:2545
    close resource://gre/modules/ExtensionCommon.jsm:2550
    unload resource://gre/modules/ExtensionCommon.jsm:912
    unload resource://gre/modules/ExtensionPageChild.jsm:261
    unload resource://gre/modules/ExtensionPageChild.jsm:298
    destroyExtensionContext resource://gre/modules/ExtensionPageChild.jsm:482
    observe resource://gre/modules/ExtensionPageChild.jsm:395
```
<br/><br/>Please, help.

**Comment by samhh** [comment]
First things first, have you installed the [host](https://github.com/samhh/bukubrow-host) and run `bukubrow --install-firefox`?

**Comment by GeorgiKarapetrov** [comment]
I had not installed the host, how silly. I did not even know the host exists.
The BukuBrow extension works now.
Thanks for your help and apologies for the inconvenience.
