### ISSUE TITLE
make build failure

### ISSUE THREAD

**Issue by larrym** [samhh/bukubrow-webext#164]
Try to build on Ubuntu Desktop 20.04

    $ make webext
    make prepare
    make[1]: Entering directory '/home/larry/Documents/bukubrow-webext'
    mkdir -p .build .clone release
    make[1]: Leaving directory '/home/larry/Documents/bukubrow-webext'
    yarn && yarn build
    00h00m00s 0/0: : ERROR: There are no scenarios; must have at least one.
    make: *** [makefile:38: webext] Error 1

**Comment by samhh** [comment]
It looks like you may have the [wrong Yarn installed](https://stackoverflow.com/questions/53471063/yarn-error-there-are-no-scenarios-must-have-at-least-one).

**Comment by larrym** [comment]
?

    sudo apt install yarn

**Comment by samhh** [comment]
Read the answers in the link I posted.
