### ISSUE TITLE
Publish on various linux repositories

### ISSUE THREAD

**Issue by CaptainQuirk** [samhh/bukubrow-webext#168]
Hi ! Thanks for your work !

It would be really great if both hosts and extension could be installed via package manager like [Browserpass](https://github.com/browserpass/browserpass-native#install-via-package-manager) can !

Thanks in advance

**Comment by samhh** [comment]
Happy to link to any distributed host as per: https://github.com/samhh/bukubrow-host/issues/3

I'm not very keen on packaging the extension but that's more down to unfamiliarity with that means of managing browser extensions.

**Comment by paulie-g** [comment]
It's not clear that this is worth doing, necessarily. I looked at packaging it for Arch, and fundamentally you simply don't know where the profile is. You could do a separate package for each browser, but I mostly use ungoogled chromium that I build myself (don't try this at home) for example, and use bukubrow in a non-default profile. There's no good, robust way of detecting all this. Granted, users can edit their PKGBUILDs (and should), but at that point it's easier to load it unpacked. Besides which Chrome/Chromium seem to break bukubrow on each version upgrade for me and I have to do that anyway to fix it.

**Comment by CaptainQuirk** [comment]
Indeed, it relates more to the bukubrow-host repository
