### ISSUE TITLE
Better Windows support

### ISSUE THREAD

**Issue by dertuxmalwieder** [SamHH/bukubrow-webext#17]
Now that buku itself is mostly compatible with being used on Windows, bukubrow could need a similar treatment (e.g. build scripts for Windows and having %USERPROFILE% added to the list of search paths for the database). I might or might not learn some Go to fix this myself, but I'm currently unable to.

**Comment by SamHH** [comment]
The request remains open here: https://github.com/SamHH/bukubrow-host/issues/5
