### ISSUE TITLE
Configurable global hotkeys

### ISSUE THREAD

**Issue by SamHH** [SamHH/bukubrow-webext#7]
Global hotkeys to consider:

- Open Bukubrow main window (already present as `Ctrl+Shift+B`)
- Quick open add bookmark window
- Context menu items?

Add all of these, and then add a link to the relevant URLs (see [here](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/commands#Updating_shortcuts)) for changing shortcuts to the README.

**Comment by SamHH** [comment]
The extension's "commands" shortcuts cannot yet be altered in WebExtensions AFAICT: https://bugzilla.mozilla.org/show_bug.cgi?id=1303384

**Comment by SamHH** [comment]
Per the reference above it would also be good to have the in-app hotkeys configurable as well. This isn't technically blocked, though I'd like to approach all of these together.

**Comment by SamHH** [comment]
The fix is targeted for Firefox 66! :confetti_ball:

**Comment by ranebrown** [comment]
The current shortcut to open the extension wasn't working for me. I found [this page](https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox) which described steps to change it. It looks like the default on Mac with Firefox 70 was `Cmd+Shift+B` which is the same as the Firefox bookmarks menu and neither of them worked.

Shortcut list for easier access:

- Ctrl+Shift+B: Open extension window (does not work with Firefox Mac)
- Ctrl+D: Open add bookmark modal
- Ctrl+O: Open all bookmarks that match the current filter
- Ctrl+R: Refresh bookmarks
- Ctrl+L: Focus search input

**Comment by SamHH** [comment]
This is probably unblocked now, need to investigate. [browserpass](https://github.com/browserpass/browserpass-extension#first-steps-in-browser-extension) seems to support it.

**Comment by SamHH** [comment]
We're unblocked! :confetti_ball:

**Comment by SamHH** [comment]
https://github.com/SamHH/bukubrow-webext/commit/291fdbc00fc6825c038e77324f94a751c34b5c58

No custom hotkeys by default, but they're all configurable in the browser. The README will be updated to reflect this.
